import stir from './imgCard/Rectangle 212.png';

/* eslint-disable import/prefer-default-export */

export const data = [
  {
    id: '1',
    image: require('../helpers/imgCard/Rectangle 212.png'), 
    value: 'Техника',
    name: 'Стиральная машина Bosch',
    text: 'Машина в хорошем состоянии. Возможен разумный торг',
    next: 'Стиральная машина в отличном состянии, чистая, без накипи. С машиной отдам новый шланг для подключения воды и упаковку средства против накипи.',
    price: '15 000 Р',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',

  },
  {
    id: '2',
    image: require('../helpers/imgCard/Rectangle 220.png'),
    value: 'Одежда',
    name: 'Шапочка',
    text: 'Шапочка детская на ребенка 7-10 лет. 60% шерст, 40% вискоза',
    next: 'Шапочка детская на ребенка 7-10 лет. 60% шерст, 40% вискоза',
    price: '500 Р ',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '3',
    image: require('../helpers/imgCard/Rectangle 367.png'),
    value: 'Одежда',
    name: 'Толстовка',
    text: 'Новая толстовка белая без принта с карманом',
    next: 'Новая толстовка белая без принта с карманом',
    price: '2 000 Р',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '4',
    image: require('../helpers/imgCard/Rectangle 352.png'),
    value: 'Спорт',
    name: 'Велосипед',
    text: 'Велосипед в отличном состоянии. Ретро-стиль',
    next: 'Велосипед в отличном состоянии. Ретро-стиль',
    price: '28 000 Р',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '5',
    image: require('../helpers/imgCard/Rectangle 350.png'),
    value: 'Техника',
    name: 'Наушники',
    text: 'Наушники почти новые. Срок эксплуатации - меньше месяца',
    next: 'Наушники почти новые. Срок эксплуатации - меньше месяца',
    price: '4 500 Р',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '6',
    image: require('../helpers/imgCard/unsplash_EXJiG6Sf_ss.png'),
    value: 'Техника',
    name: 'Кофемашина',
    text: 'Кофемашина с капучинатором. Пакет кофе 1 кг. - в подарок',
    next: 'Кофемашина с капучинатором. Пакет кофе 1 кг. - в подарок',
    price: '8 500 Р',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '7',
    image: require('../helpers/imgCard/unsplash_MC_p9Oti0E0.png'),
    value: 'Одежда',
    name: 'Сумка женская',
    text: 'Итальянска сумка из натуральной кожи. Качественная фурнитура, состояние новой',
    next: 'Итальянска сумка из натуральной кожи. Качественная фурнитура, состояние новой',
    price: '7 500 Р ',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '8',
    image: require('../helpers/imgCard/unsplash_3OZr-hLbsq0.png'),
    value: 'Одежда',
    name: 'Ботинки мужские зимние',
    text: 'Ботинки почти новые, качественные, теплые. Носили 2 недели',
    next: 'Ботинки почти новые, качественные, теплые. Носили 2 недели',
    price: '8 000 Р ',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
  {
    id: '9',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    value: 'Спорт',
    name: 'Доска для сноубординга',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    Date: '14 апреля 2021',
    look: '356',
    publ: 'да',
  },
];


export const itemsCard = [
  { name: 'Чепчик', 
    id: '10', 
    value: 'Одежда', 
    Date: '12 апреля 2022', 
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да' 
},
  {
    name: 'Самовар',
    id: '11',
    value: 'Товары для дома',
    Date: '12 апреля 2022',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    price: '43 000 Р ',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    publ: 'да',
  },
  {
    name: 'Стиральная машина LG',
    id: '12',
    value: 'Техника',
    Date: '11 апреля 2022',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да',
  },
  {
    name: 'Часы Rolex',
    id: '13',
    value: 'Аксессуары',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    Date: '10 апреля 2022',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да',
  },
  {
    name: 'Lada Kalina',
    id: '14',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    value: 'Автомобили',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    Date: '8 апреля 2022',
    publ: 'да',
  },
  {
    name: 'Спортивный велосипед',
    id: '15',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    value: 'Спорт',
    Date: '16 апреля 2022',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да',
  },
  {
    name: 'Ботинки поношенные',
    id: '16',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    value: 'Одежда',
    Date: '25 апреля 2022',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да',
  },
  {
    name: 'Приставка Dendy',
    id: '17',
    value: 'Техника',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    Date: '18 апреля 2022',
    text: 'Качественная красиваядоска с креплениями',
    next: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    publ: 'да',
  },
  
];
