import stir from './imgCard/Rectangle 212.png';

/* eslint-disable import/prefer-default-export */

export const data = [
  {
    id: '1',
    image: require('../helpers/imgCard/Rectangle 212.png'),
    value: 'Техника',
    name: 'Стиральная машина Bosch',
    text: 'Машина в хорошем состоянии. Возможен разумный торг',
    next: 'Стиральная машина в отличном состянии, чистая, без накипи. С машиной отдам новый шланг для подключения воды и упаковку средства против накипи.',
    price: '15 000 Р',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '2',
    image: require('../helpers/imgCard/Rectangle 220.png'),
    value: 'Одежда',
    name: 'Шапочка',
    text: 'Шапочка детская на ребенка 7-10 лет. 60% шерст, 40% вискоза',
    next: 'Какой-то текст',
    price: '500 Р ',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '3',
    image: require('../helpers/imgCard/Rectangle 367.png'),
    value: 'Одежда',
    name: 'Толстовка',
    text: 'Новая толстовка белая без принта с карманом',
    price: '2 000 Р',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '4',
    image: require('../helpers/imgCard/Rectangle 352.png'),
    value: 'Спорт',
    name: 'Велосипед',
    text: 'Велосипед в отличном состоянии. Ретро-стиль',
    price: '28 000 Р',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '5',
    image: require('../helpers/imgCard/Rectangle 350.png'),
    value: 'Техника',
    name: 'Наушники',
    text: 'Наушники почти новые. Срок эксплуатации - меньше месяца',
    price: '4 500 Р',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '6',
    image: require('../helpers/imgCard/unsplash_EXJiG6Sf_ss.png'),
    value: 'Техника',
    name: 'Кофемашина',
    text: 'Кофемашина с капучинатором. Пакет кофе 1 кг. - в подарок',
    price: '8 500 Р',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '7',
    image: require('../helpers/imgCard/unsplash_MC_p9Oti0E0.png'),
    value: 'Одежда',
    name: 'Сумка женская',
    text: 'Итальянска сумка из натуральной кожи. Качественная фурнитура, состояние новой',
    price: '7 500 Р ',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '8',
    image: require('../helpers/imgCard/unsplash_3OZr-hLbsq0.png'),
    value: 'Одежда',
    name: 'Ботинки мужские зимние',
    text: 'Ботинки почти новые, качественные, теплые. Носили 2 недели',
    price: '8 000 Р ',
    data: '14 апреля 2021',
    look: '356',
  },
  {
    id: '9',
    image: require('../helpers/imgCard/unsplash_j5asemKMmQY.png'),
    value: 'Спорт',
    name: 'Доска для сноубординга',
    text: 'Качественная красиваядоска с креплениями',
    price: '43 000 Р ',
    data: '14 апреля 2021',
    look: '356',
  },
];
